export const USER_GET = "GET_USER"
export const USER_POST = "POST_USER"
export const USER_PUT = "PUT_USER"
export const USER_PATCH = "PATCH_USER"
export const USER_DELETE = "DELETE_USER"
export const USER_SUCCESS = "SUCCESS_USER"
export const STUDENT_SUCCESS = "STUDENT_SUCCESS"
export const STUDENT_GET = "GET_STUDENT"